### PR TITLE
Add Gitlab with PostgreSQL, Redis store and Nginx YAML blueprint

### PR DESCRIPTION
**Pull request by tbouron**
Hi there.

Here is a new YAML blueprint that will deploy a new instance of Gitlab with PostgreSQL, Redis store and Nginx server.

Any comment / suggestion / improvement on this will be appreciated.

### CODE REVIEW

**Comment by duncangrant** [comment]
Should possibly make it clear in comments that will only work with debian based linux?

**Comment by mikezaccardo** [comment]
@duncangrant Agreed, should add:

```
 provisioning.properties:
      osFamily: debian
```

**Comment by tbouron** [comment]
+1 on @mikezaccardo suggestion, it looks like a very elegant solution.

Once I made my changes, do you want me to squash my commits or the PR?

**Comment by mikezaccardo** [comment]
I'm not sure about our policy on squashing vs leaving an audit trail. Will
kick this question up to dev since I've wondered about it a few times
myself.
On Jun 17, 2015 4:09 AM, "Thomas Bouron" notifications@github.com wrote:

> +1 on @mikezaccardo https://github.com/mikezaccardo suggestion, it
> looks like a very elegant solution.
> 
> Once I made my changes, do you want me to squash my commits or the PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brooklyncentral/blueprint-library/pull/1#issuecomment-112709244
> .

## 

Cloudsoft Corporation Limited, Registered in Scotland No: SC349230. 
 Registered Office: 13 Dryden Place, Edinburgh, EH9 1RP

This e-mail message is confidential and for use by the addressee only. If 
the message is received by anyone other than the addressee, please return 
the message to the sender by replying to it and then delete the message 
from your computer. Internet e-mails are not necessarily secure. Cloudsoft 
Corporation Limited does not accept responsibility for changes made to this 
message after it was sent.

Whilst all reasonable care has been taken to avoid the transmission of 
viruses, it is the responsibility of the recipient to ensure that the 
onward transmission, opening or use of this message and any attachments 
will not adversely affect its systems or data. No responsibility is 
accepted by Cloudsoft Corporation Limited in this regard and the recipient 
should carry out such virus and other checks as it considers appropriate.

**Comment by mikezaccardo** [comment]
Based on Martin's answer, I'd say go ahead and squash.
On Jun 17, 2015 9:08 AM, "Mike Zaccardo" mike.zaccardo@cloudsoftcorp.com
wrote:

> I'm not sure about our policy on squashing vs leaving an audit trail. Will
> kick this question up to dev since I've wondered about it a few times
> myself.
> On Jun 17, 2015 4:09 AM, "Thomas Bouron" notifications@github.com wrote:
> 
> > +1 on @mikezaccardo https://github.com/mikezaccardo suggestion, it
> > looks like a very elegant solution.
> > 
> > Once I made my changes, do you want me to squash my commits or the PR?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/brooklyncentral/blueprint-library/pull/1#issuecomment-112709244
> > .

## 

Cloudsoft Corporation Limited, Registered in Scotland No: SC349230. 
 Registered Office: 13 Dryden Place, Edinburgh, EH9 1RP

This e-mail message is confidential and for use by the addressee only. If 
the message is received by anyone other than the addressee, please return 
the message to the sender by replying to it and then delete the message 
from your computer. Internet e-mails are not necessarily secure. Cloudsoft 
Corporation Limited does not accept responsibility for changes made to this 
message after it was sent.

Whilst all reasonable care has been taken to avoid the transmission of 
viruses, it is the responsibility of the recipient to ensure that the 
onward transmission, opening or use of this message and any attachments 
will not adversely affect its systems or data. No responsibility is 
accepted by Cloudsoft Corporation Limited in this regard and the recipient 
should carry out such virus and other checks as it considers appropriate.

**Comment by tbouron** [comment]
Added the provisioning.properties and squashed my commits.

**Comment by grkvlt** [comment]
Thanks @tbouron this looks good, so I'm going to merge now

**Pull request merged**
